### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by AtomicAlienZ** [AtomicAlienZ/GURPSGrid#1]
- [ ] Refactor to use selectors everywhere
- [ ] Refactor overlays to be derived data
- [ ] Refactor `activeHexes`: use `floorAreas` instead
- [ ] Add floor areas "flattening": remove overlapped hexes from user-selected areas
- [ ] Think through object constructor
- [ ] Add objects constructor & placement
- [ ] Finally start working on some server, auth, that kind of stuff
